"""Block definitions and mappings."""

from typing import Any, Dict, List


class BlockDefinitionService:
    """Provides available block definitions for the frontend."""

    def get_available_blocks(self) -> Dict[str, List[Dict[str, Any]]]:
        """Return all available blocks organized by category."""
        return {
            "events": [
                # Player Events
                {
                    "id": "player-join",
                    "name": "PlayerJoinEvent",
                    "type": "event",
                    "description": "Fired when a player joins the server",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-quit",
                    "name": "PlayerQuitEvent",
                    "type": "event",
                    "description": "Fired when a player leaves the server",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-move",
                    "name": "PlayerMoveEvent",
                    "type": "event",
                    "description": "Fired when a player moves or rotates",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-chat",
                    "name": "AsyncPlayerChatEvent",
                    "type": "event",
                    "description": "Fired when a player sends a chat message",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-death",
                    "name": "PlayerDeathEvent",
                    "type": "event",
                    "description": "Fired when a player dies",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-respawn",
                    "name": "PlayerRespawnEvent",
                    "type": "event",
                    "description": "Fired when a player respawns after death",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-interact",
                    "name": "PlayerInteractEvent",
                    "type": "event",
                    "description": "Fired when a player interacts (click) with block or air",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-interact-entity",
                    "name": "PlayerInteractEntityEvent",
                    "type": "event",
                    "description": "Fired when a player right-clicks an entity",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-toggle-sneak",
                    "name": "PlayerToggleSneakEvent",
                    "type": "event",
                    "description": "Fired when a player starts or stops sneaking",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-toggle-sprint",
                    "name": "PlayerToggleSprintEvent",
                    "type": "event",
                    "description": "Fired when a player starts or stops sprinting",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-drop-item",
                    "name": "PlayerDropItemEvent",
                    "type": "event",
                    "description": "Fired when a player drops an item",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-pickup-item",
                    "name": "EntityPickupItemEvent",
                    "type": "event",
                    "description": "Fired when a player picks up an item",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                # Block Events
                {
                    "id": "block-break",
                    "name": "BlockBreakEvent",
                    "type": "event",
                    "description": "Fired when a player breaks a block",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-place",
                    "name": "BlockPlaceEvent",
                    "type": "event",
                    "description": "Fired when a player places a block",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-burn",
                    "name": "BlockBurnEvent",
                    "type": "event",
                    "description": "Fired when a block is burned by fire",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-ignite",
                    "name": "BlockIgniteEvent",
                    "type": "event",
                    "description": "Fired when a block catches fire",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                # Entity Events
                {
                    "id": "entity-damage",
                    "name": "EntityDamageEvent",
                    "type": "event",
                    "description": "Fired when any entity takes damage",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "entity-damage-by-entity",
                    "name": "EntityDamageByEntityEvent",
                    "type": "event",
                    "description": "Fired when an entity damages another (PvP/combat)",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "entity-death",
                    "name": "EntityDeathEvent",
                    "type": "event",
                    "description": "Fired when any entity dies",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "creature-spawn",
                    "name": "CreatureSpawnEvent",
                    "type": "event",
                    "description": "Fired when a mob spawns",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                # World Events
                {
                    "id": "weather-change",
                    "name": "WeatherChangeEvent",
                    "type": "event",
                    "description": "Fired when weather changes (rain starts/stops)",
                    "color": "#9b59b6",
                    "properties": [],
                    "category": "world",
                },
            ],
            "actions": [
                {
                    "id": "send-message",
                    "name": "SendMessage",
                    "type": "action",
                    "description": "Send a message to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Enter message..."},
                    ],
                },
                {
                    "id": "broadcast-message",
                    "name": "BroadcastMessage",
                    "type": "action",
                    "description": "Broadcast a message to all players",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Enter broadcast message..."},
                    ],
                },
                {
                    "id": "give-item",
                    "name": "GiveItem",
                    "type": "action",
                    "description": "Give an item to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "e.g., DIAMOND"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "set-health",
                    "name": "SetHealth",
                    "type": "action",
                    "description": "Set the player health",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "health", "type": "string", "required": True, "placeholder": "20.0"},
                    ],
                },
                {
                    "id": "set-hunger",
                    "name": "SetHunger",
                    "type": "action",
                    "description": "Set the player food level",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "hunger", "type": "string", "required": True, "placeholder": "20"},
                    ],
                },
                {
                    "id": "cancel-event",
                    "name": "CancelEvent",
                    "type": "action",
                    "description": "Cancel the current event",
                    "color": "#e74c3c",
                    "properties": [],
                },
                {
                    "id": "play-sound",
                    "name": "PlaySound",
                    "type": "action",
                    "description": "Play a sound to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "sound", "type": "string", "required": True, "placeholder": "ENTITY_EXPERIENCE_ORB_PICKUP"},
                        {"name": "volume", "type": "string", "required": False, "placeholder": "1.0"},
                        {"name": "pitch", "type": "string", "required": False, "placeholder": "1.0"},
                    ],
                },
                {
                    "id": "teleport-player",
                    "name": "TeleportPlayer",
                    "type": "action",
                    "description": "Teleport the player to coordinates",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "x", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y", "type": "string", "required": True, "placeholder": "64"},
                        {"name": "z", "type": "string", "required": True, "placeholder": "0"},
                    ],
                },
                {
                    "id": "add-experience",
                    "name": "AddExperience",
                    "type": "action",
                    "description": "Give experience points to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "amount", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "send-title",
                    "name": "SendTitle",
                    "type": "action",
                    "description": "Show a title on the player screen",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "title", "type": "string", "required": True, "placeholder": "Title text"},
                        {"name": "subtitle", "type": "string", "required": False, "placeholder": "Subtitle text"},
                        {"name": "fadeIn", "type": "string", "required": False, "placeholder": "10"},
                        {"name": "stay", "type": "string", "required": False, "placeholder": "70"},
                        {"name": "fadeOut", "type": "string", "required": False, "placeholder": "20"},
                    ],
                },
                {
                    "id": "console-log",
                    "name": "ConsoleLog",
                    "type": "action",
                    "description": "Log a message to the server console",
                    "color": "#95a5a6",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Log message..."},
                    ],
                },
                {
                    "id": "drop-item",
                    "name": "DropItem",
                    "type": "action",
                    "description": "Drop an item at the player location",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "DIAMOND"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "set-game-mode",
                    "name": "SetGameMode",
                    "type": "action",
                    "description": "Change the player's game mode",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "gameMode", "type": "string", "required": True, "placeholder": "SURVIVAL"},
                    ],
                },
                {
                    "id": "add-potion-effect",
                    "name": "AddPotionEffect",
                    "type": "action",
                    "description": "Apply a potion effect to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "effectType", "type": "string", "required": True, "placeholder": "SPEED"},
                        {"name": "duration", "type": "string", "required": True, "placeholder": "200"},
                        {"name": "amplifier", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "remove-potion-effect",
                    "name": "RemovePotionEffect",
                    "type": "action",
                    "description": "Remove a potion effect from the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "effectType", "type": "string", "required": True, "placeholder": "SPEED"},
                    ],
                },
                {
                    "id": "set-velocity",
                    "name": "SetVelocity",
                    "type": "action",
                    "description": "Set player velocity (launch player)",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "x", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y", "type": "string", "required": True, "placeholder": "1"},
                        {"name": "z", "type": "string", "required": True, "placeholder": "0"},
                    ],
                },
                {
                    "id": "send-actionbar",
                    "name": "SendActionBar",
                    "type": "action",
                    "description": "Show a message in the action bar",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Action bar text..."},
                    ],
                },
                {
                    "id": "spawn-particle",
                    "name": "SpawnParticle",
                    "type": "action",
                    "description": "Spawn particles at player location",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "particle", "type": "string", "required": True, "placeholder": "HEART"},
                        {"name": "count", "type": "string", "required": False, "placeholder": "10"},
                    ],
                },
                {
                    "id": "kill-player",
                    "name": "KillPlayer",
                    "type": "action",
                    "description": "Kill the player instantly",
                    "color": "#e74c3c",
                    "properties": [],
                },
                {
                    "id": "damage-player",
                    "name": "DamagePlayer",
                    "type": "action",
                    "description": "Deal damage to the player",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "amount", "type": "string", "required": True, "placeholder": "5.0"},
                    ],
                },
                {
                    "id": "clear-inventory",
                    "name": "ClearInventory",
                    "type": "action",
                    "description": "Clear the player's inventory",
                    "color": "#e74c3c",
                    "properties": [],
                },
                {
                    "id": "set-experience-level",
                    "name": "SetExperienceLevel",
                    "type": "action",
                    "description": "Set the player's XP level",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "level", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "execute-command",
                    "name": "ExecuteCommand",
                    "type": "action",
                    "description": "Execute a command as the player",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "command", "type": "string", "required": True, "placeholder": "say Hello"},
                    ],
                },
                {
                    "id": "execute-console-command",
                    "name": "ExecuteConsoleCommand",
                    "type": "action",
                    "description": "Execute a command from the console",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "command", "type": "string", "required": True, "placeholder": "give %player% diamond 1"},
                    ],
                },
                {
                    "id": "kick-player",
                    "name": "KickPlayer",
                    "type": "action",
                    "description": "Kick the player from the server",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "reason", "type": "string", "required": False, "placeholder": "You have been kicked!"},
                    ],
                },
                # World Actions
                {
                    "id": "set-time",
                    "name": "SetTime",
                    "type": "action",
                    "description": "Set the world time (0=sunrise, 6000=noon, 18000=midnight)",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "time", "type": "string", "required": True, "placeholder": "6000"},
                    ],
                },
                {
                    "id": "set-weather",
                    "name": "SetWeather",
                    "type": "action",
                    "description": "Set the world weather",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "storm", "type": "string", "required": True, "placeholder": "false"},
                        {"name": "duration", "type": "string", "required": False, "placeholder": "6000"},
                    ],
                },
                {
                    "id": "strike-lightning",
                    "name": "StrikeLightning",
                    "type": "action",
                    "description": "Strike lightning at player location",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "damage", "type": "string", "required": False, "placeholder": "true"},
                    ],
                },
                {
                    "id": "create-explosion",
                    "name": "CreateExplosion",
                    "type": "action",
                    "description": "Create an explosion at player location",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "power", "type": "string", "required": True, "placeholder": "4.0"},
                        {"name": "fire", "type": "string", "required": False, "placeholder": "false"},
                        {"name": "breakBlocks", "type": "string", "required": False, "placeholder": "false"},
                    ],
                },
                # Visibility Actions
                {
                    "id": "set-glowing",
                    "name": "SetGlowing",
                    "type": "action",
                    "description": "Make player glow (visible through walls)",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "glowing", "type": "string", "required": True, "placeholder": "true"},
                    ],
                },
                {
                    "id": "set-invisible",
                    "name": "SetInvisible",
                    "type": "action",
                    "description": "Make player invisible",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "invisible", "type": "string", "required": True, "placeholder": "true"},
                    ],
                },
                {
                    "id": "allow-flight",
                    "name": "AllowFlight",
                    "type": "action",
                    "description": "Enable or disable flight for the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "allow", "type": "string", "required": True, "placeholder": "true"},
                        {"name": "startFlying", "type": "string", "required": False, "placeholder": "false"},
                    ],
                },
                {
                    "id": "set-fire-ticks",
                    "name": "SetOnFire",
                    "type": "action",
                    "description": "Set player on fire",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "ticks", "type": "string", "required": True, "placeholder": "100"},
                    ],
                },
            ],
            "custom_options": [
                {
                    "id": "custom-condition",
                    "name": "Custom Condition",
                    "type": "custom-condition",
                    "description": "Write custom Java logic for a condition",
                    "color": "#f39c12",
                    "properties": [],
                },
                {
                    "id": "custom-action",
                    "name": "Custom Action",
                    "type": "custom-action",
                    "description": "Write custom Java code for an action",
                    "color": "#9b59b6",
                    "properties": [],
                },
            ],
        }
