"""Block definitions and mappings."""

from typing import Any, Dict, List


class BlockDefinitionService:
    """Provides available block definitions for the frontend."""

    def get_available_blocks(self) -> Dict[str, List[Dict[str, Any]]]:
        """Return all available blocks organized by category."""
        return {
            "events": [
                # Player Events
                {
                    "id": "player-join",
                    "name": "PlayerJoinEvent",
                    "type": "event",
                    "description": "Fired when a player joins the server",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-quit",
                    "name": "PlayerQuitEvent",
                    "type": "event",
                    "description": "Fired when a player leaves the server",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-move",
                    "name": "PlayerMoveEvent",
                    "type": "event",
                    "description": "Fired when a player moves or rotates",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-chat",
                    "name": "AsyncPlayerChatEvent",
                    "type": "event",
                    "description": "Fired when a player sends a chat message",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-death",
                    "name": "PlayerDeathEvent",
                    "type": "event",
                    "description": "Fired when a player dies",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-respawn",
                    "name": "PlayerRespawnEvent",
                    "type": "event",
                    "description": "Fired when a player respawns after death",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-interact",
                    "name": "PlayerInteractEvent",
                    "type": "event",
                    "description": "Fired when a player interacts (click) with block or air",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-interact-entity",
                    "name": "PlayerInteractEntityEvent",
                    "type": "event",
                    "description": "Fired when a player right-clicks an entity",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-toggle-sneak",
                    "name": "PlayerToggleSneakEvent",
                    "type": "event",
                    "description": "Fired when a player starts or stops sneaking",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-toggle-sprint",
                    "name": "PlayerToggleSprintEvent",
                    "type": "event",
                    "description": "Fired when a player starts or stops sprinting",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-drop-item",
                    "name": "PlayerDropItemEvent",
                    "type": "event",
                    "description": "Fired when a player drops an item",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                {
                    "id": "player-pickup-item",
                    "name": "EntityPickupItemEvent",
                    "type": "event",
                    "description": "Fired when a player picks up an item",
                    "color": "#3498db",
                    "properties": [],
                    "category": "player",
                },
                # Block Events
                {
                    "id": "block-break",
                    "name": "BlockBreakEvent",
                    "type": "event",
                    "description": "Fired when a player breaks a block",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-place",
                    "name": "BlockPlaceEvent",
                    "type": "event",
                    "description": "Fired when a player places a block",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-burn",
                    "name": "BlockBurnEvent",
                    "type": "event",
                    "description": "Fired when a block is burned by fire",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-ignite",
                    "name": "BlockIgniteEvent",
                    "type": "event",
                    "description": "Fired when a block catches fire",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                {
                    "id": "block-grow",
                    "name": "BlockGrowEvent",
                    "type": "event",
                    "description": "Fired when a block grows (crops, trees, vines)",
                    "color": "#e67e22",
                    "properties": [],
                    "category": "block",
                },
                # Entity Events
                {
                    "id": "entity-damage",
                    "name": "EntityDamageEvent",
                    "type": "event",
                    "description": "Fired when any entity takes damage",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "entity-damage-by-entity",
                    "name": "EntityDamageByEntityEvent",
                    "type": "event",
                    "description": "Fired when an entity damages another (PvP/combat)",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "entity-death",
                    "name": "EntityDeathEvent",
                    "type": "event",
                    "description": "Fired when any entity dies",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "creature-spawn",
                    "name": "CreatureSpawnEvent",
                    "type": "event",
                    "description": "Fired when a mob spawns",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                {
                    "id": "entity-spawn",
                    "name": "EntitySpawnEvent",
                    "type": "event",
                    "description": "Fired when any entity spawns",
                    "color": "#e74c3c",
                    "properties": [],
                    "category": "entity",
                },
                # World Events
                {
                    "id": "weather-change",
                    "name": "WeatherChangeEvent",
                    "type": "event",
                    "description": "Fired when weather changes (rain starts/stops)",
                    "color": "#9b59b6",
                    "properties": [],
                    "category": "world",
                },
                {
                    "id": "thunder-change",
                    "name": "ThunderChangeEvent",
                    "type": "event",
                    "description": "Fired when thunder starts/stops",
                    "color": "#9b59b6",
                    "properties": [],
                    "category": "world",
                },
                {
                    "id": "server-list-ping",
                    "name": "ServerListPingEvent",
                    "type": "event",
                    "description": "Fired when the server list is pinged",
                    "color": "#9b59b6",
                    "properties": [],
                    "category": "server",
                },
                {
                    "id": "on-gui-click",
                    "name": "OnGUIClick",
                    "type": "event",
                    "description": "Fired when a player clicks inside an inventory GUI",
                    "color": "#1abc9c",
                    "category": "player",
                    "properties": [
                        {"name": "guiTitle", "type": "string", "required": False, "placeholder": "My Menu"},
                        {"name": "slot", "type": "string", "required": False, "placeholder": "-1 (any slot)"},
                        {"name": "cancelEvent", "type": "string", "required": False, "placeholder": "true"},
                    ],
                },
                # Command Events
                {
                    "id": "command-event",
                    "name": "CommandEvent",
                    "type": "event",
                    "description": "Triggered when a player runs a custom command",
                    "color": "#e74c3c",
                    "category": "server",
                    "properties": [
                        {"name": "commandName", "type": "string", "required": True, "placeholder": "mycommand"},
                        {"name": "commandDescription", "type": "string", "required": False, "placeholder": "My custom command"},
                        {"name": "commandUsage", "type": "string", "required": False, "placeholder": "/<command>"},
                        {"name": "commandPermission", "type": "string", "required": False, "placeholder": "myplugin.mycommand"},
                        {"name": "commandAliases", "type": "string", "required": False, "placeholder": "mc,mycmd"},
                        {"name": "commandTabCompletions", "type": "string", "required": False, "placeholder": "reload,status,help"},
                    ],
                },
            ],
            "actions": [
                {
                    "id": "send-message",
                    "name": "SendMessage",
                    "type": "action",
                    "description": "Send a message to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Enter message..."},
                    ],
                },
                {
                    "id": "broadcast-message",
                    "name": "BroadcastMessage",
                    "type": "action",
                    "description": "Broadcast a message to all players",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Enter broadcast message..."},
                    ],
                },
                {
                    "id": "give-item",
                    "name": "GiveItem",
                    "type": "action",
                    "description": "Give an item to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "e.g., DIAMOND"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                        {"name": "displayName", "type": "string", "required": False, "placeholder": "Custom item name (supports &color codes)"},
                        {"name": "lore", "type": "string", "required": False, "placeholder": "Line 1|Line 2|Line 3 (use | to separate lines)"},
                        {"name": "enchantments", "type": "string", "required": False, "placeholder": "SHARPNESS:5,UNBREAKING:3"},
                        {"name": "itemFlags", "type": "string", "required": False, "placeholder": "HIDE_ENCHANTS,HIDE_ATTRIBUTES"},
                    ],
                },
                {
                    "id": "set-health",
                    "name": "SetHealth",
                    "type": "action",
                    "description": "Set the player health",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "health", "type": "string", "required": True, "placeholder": "20.0"},
                    ],
                },
                {
                    "id": "set-hunger",
                    "name": "SetHunger",
                    "type": "action",
                    "description": "Set the player food level",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "hunger", "type": "string", "required": True, "placeholder": "20"},
                    ],
                },
                {
                    "id": "cancel-event",
                    "name": "CancelEvent",
                    "type": "action",
                    "description": "Cancel the current event",
                    "color": "#e74c3c",
                    "properties": [],
                },
                {
                    "id": "play-sound",
                    "name": "PlaySound",
                    "type": "action",
                    "description": "Play a sound to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "sound", "type": "string", "required": True, "placeholder": "ENTITY_EXPERIENCE_ORB_PICKUP"},
                        {"name": "volume", "type": "string", "required": False, "placeholder": "1.0"},
                        {"name": "pitch", "type": "string", "required": False, "placeholder": "1.0"},
                    ],
                },
                {
                    "id": "teleport-player",
                    "name": "TeleportPlayer",
                    "type": "action",
                    "description": "Teleport the player to coordinates",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "x", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y", "type": "string", "required": True, "placeholder": "64"},
                        {"name": "z", "type": "string", "required": True, "placeholder": "0"},
                    ],
                },
                {
                    "id": "add-experience",
                    "name": "AddExperience",
                    "type": "action",
                    "description": "Give experience points to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "amount", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "send-title",
                    "name": "SendTitle",
                    "type": "action",
                    "description": "Show a title on the player screen",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "title", "type": "string", "required": True, "placeholder": "Title text"},
                        {"name": "subtitle", "type": "string", "required": False, "placeholder": "Subtitle text"},
                        {"name": "fadeIn", "type": "string", "required": False, "placeholder": "10"},
                        {"name": "stay", "type": "string", "required": False, "placeholder": "70"},
                        {"name": "fadeOut", "type": "string", "required": False, "placeholder": "20"},
                    ],
                },
                {
                    "id": "console-log",
                    "name": "ConsoleLog",
                    "type": "action",
                    "description": "Log a message to the server console",
                    "color": "#95a5a6",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Log message..."},
                    ],
                },
                {
                    "id": "drop-item",
                    "name": "DropItem",
                    "type": "action",
                    "description": "Drop an item at the player location",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "DIAMOND"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "set-game-mode",
                    "name": "SetGameMode",
                    "type": "action",
                    "description": "Change the player's game mode",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "gameMode", "type": "string", "required": True, "placeholder": "SURVIVAL"},
                    ],
                },
                {
                    "id": "add-potion-effect",
                    "name": "AddPotionEffect",
                    "type": "action",
                    "description": "Apply a potion effect to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "effectType", "type": "string", "required": True, "placeholder": "SPEED"},
                        {"name": "duration", "type": "string", "required": True, "placeholder": "200"},
                        {"name": "amplifier", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "remove-potion-effect",
                    "name": "RemovePotionEffect",
                    "type": "action",
                    "description": "Remove a potion effect from the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "effectType", "type": "string", "required": True, "placeholder": "SPEED"},
                    ],
                },
                {
                    "id": "set-velocity",
                    "name": "SetVelocity",
                    "type": "action",
                    "description": "Set player velocity (launch player)",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "x", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y", "type": "string", "required": True, "placeholder": "1"},
                        {"name": "z", "type": "string", "required": True, "placeholder": "0"},
                    ],
                },
                {
                    "id": "send-actionbar",
                    "name": "SendActionBar",
                    "type": "action",
                    "description": "Show a message in the action bar",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Action bar text..."},
                    ],
                },
                {
                    "id": "spawn-particle",
                    "name": "SpawnParticle",
                    "type": "action",
                    "description": "Spawn particles at player location",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "particle", "type": "string", "required": True, "placeholder": "HEART"},
                        {"name": "count", "type": "string", "required": False, "placeholder": "10"},
                    ],
                },
                {
                    "id": "kill-player",
                    "name": "KillPlayer",
                    "type": "action",
                    "description": "Kill the player instantly",
                    "color": "#e74c3c",
                    "properties": [],
                },
                {
                    "id": "damage-player",
                    "name": "DamagePlayer",
                    "type": "action",
                    "description": "Deal damage to the player",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "amount", "type": "string", "required": True, "placeholder": "5.0"},
                    ],
                },
                {
                    "id": "clear-inventory",
                    "name": "ClearInventory",
                    "type": "action",
                    "description": "Clear the player's inventory",
                    "color": "#e74c3c",
                    "properties": [],
                },
                {
                    "id": "set-experience-level",
                    "name": "SetExperienceLevel",
                    "type": "action",
                    "description": "Set the player's XP level",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "level", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "execute-command",
                    "name": "ExecuteCommand",
                    "type": "action",
                    "description": "Execute a command as the player",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "command", "type": "string", "required": True, "placeholder": "say Hello"},
                    ],
                },
                {
                    "id": "execute-console-command",
                    "name": "ExecuteConsoleCommand",
                    "type": "action",
                    "description": "Execute a command from the console",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "command", "type": "string", "required": True, "placeholder": "give %player% diamond 1"},
                    ],
                },
                {
                    "id": "kick-player",
                    "name": "KickPlayer",
                    "type": "action",
                    "description": "Kick the player from the server",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "reason", "type": "string", "required": False, "placeholder": "You have been kicked!"},
                    ],
                },
                # World Actions
                {
                    "id": "set-time",
                    "name": "SetTime",
                    "type": "action",
                    "description": "Set the world time (0=sunrise, 6000=noon, 18000=midnight)",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "time", "type": "string", "required": True, "placeholder": "6000"},
                    ],
                },
                {
                    "id": "set-weather",
                    "name": "SetWeather",
                    "type": "action",
                    "description": "Set the world weather",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "storm", "type": "string", "required": True, "placeholder": "false"},
                        {"name": "duration", "type": "string", "required": False, "placeholder": "6000"},
                    ],
                },
                {
                    "id": "strike-lightning",
                    "name": "StrikeLightning",
                    "type": "action",
                    "description": "Strike lightning at player location",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "damage", "type": "string", "required": False, "placeholder": "true"},
                    ],
                },
                {
                    "id": "create-explosion",
                    "name": "CreateExplosion",
                    "type": "action",
                    "description": "Create an explosion at player location",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "power", "type": "string", "required": True, "placeholder": "4.0"},
                        {"name": "fire", "type": "string", "required": False, "placeholder": "false"},
                        {"name": "breakBlocks", "type": "string", "required": False, "placeholder": "false"},
                    ],
                },
                # Visibility Actions
                {
                    "id": "set-glowing",
                    "name": "SetGlowing",
                    "type": "action",
                    "description": "Make player glow (visible through walls)",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "glowing", "type": "string", "required": True, "placeholder": "true"},
                    ],
                },
                {
                    "id": "set-invisible",
                    "name": "SetInvisible",
                    "type": "action",
                    "description": "Make player invisible",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "invisible", "type": "string", "required": True, "placeholder": "true"},
                    ],
                },
                {
                    "id": "allow-flight",
                    "name": "AllowFlight",
                    "type": "action",
                    "description": "Enable or disable flight for the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "allow", "type": "string", "required": True, "placeholder": "true"},
                        {"name": "startFlying", "type": "string", "required": False, "placeholder": "false"},
                    ],
                },
                {
                    "id": "set-fire-ticks",
                    "name": "SetOnFire",
                    "type": "action",
                    "description": "Set player on fire",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "ticks", "type": "string", "required": True, "placeholder": "100"},
                    ],
                },
                {
                    "id": "send-console-message",
                    "name": "SendConsoleMessage",
                    "type": "action",
                    "description": "Send a message to the server console",
                    "color": "#95a5a6",
                    "properties": [
                        {"name": "message", "type": "string", "required": True, "placeholder": "Console message"},
                    ],
                },
                {
                    "id": "remove-item",
                    "name": "RemoveItem",
                    "type": "action",
                    "description": "Remove an item from the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "DIAMOND"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "set-item-in-hand",
                    "name": "SetItemInHand",
                    "type": "action",
                    "description": "Set the item in the player's hand",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "DIAMOND_SWORD"},
                        {"name": "hand", "type": "string", "required": False, "placeholder": "MAIN_HAND"},
                    ],
                },
                {
                    "id": "set-saturation",
                    "name": "SetSaturation",
                    "type": "action",
                    "description": "Set player saturation",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "saturation", "type": "string", "required": True, "placeholder": "5.0"},
                    ],
                },
                {
                    "id": "set-level",
                    "name": "SetLevel",
                    "type": "action",
                    "description": "Set the player's XP level",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "level", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "apply-potion-effect",
                    "name": "ApplyPotionEffect",
                    "type": "action",
                    "description": "Apply a potion effect to the player",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "effectType", "type": "string", "required": True, "placeholder": "SPEED"},
                        {"name": "duration", "type": "string", "required": True, "placeholder": "200"},
                        {"name": "amplifier", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "set-custom-name",
                    "name": "SetCustomName",
                    "type": "action",
                    "description": "Set the player's custom name",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "name", "type": "string", "required": True, "placeholder": "Player Name"},
                    ],
                },
                {
                    "id": "grant-permission",
                    "name": "GrantPermission",
                    "type": "action",
                    "description": "Grant or deny a permission to the player",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "permission", "type": "string", "required": True, "placeholder": "vip.commands"},
                        {"name": "value", "type": "string", "required": True, "placeholder": "true"},
                    ],
                },
                {
                    "id": "set-metadata",
                    "name": "SetMetadata",
                    "type": "action",
                    "description": "Set metadata on the player",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "key", "type": "string", "required": True, "placeholder": "key"},
                        {"name": "value", "type": "string", "required": True, "placeholder": "value"},
                    ],
                },
                {
                    "id": "set-block-type",
                    "name": "SetBlockType",
                    "type": "action",
                    "description": "Set the block type at target location",
                    "color": "#e67e22",
                    "properties": [
                        {"name": "blockType", "type": "string", "required": True, "placeholder": "STONE"},
                    ],
                },
                {
                    "id": "remove-block",
                    "name": "RemoveBlock",
                    "type": "action",
                    "description": "Remove the target block",
                    "color": "#e67e22",
                    "properties": [],
                },
                {
                    "id": "fill-region",
                    "name": "FillRegion",
                    "type": "action",
                    "description": "Fill a region with a block type",
                    "color": "#e67e22",
                    "properties": [
                        {"name": "x1", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y1", "type": "string", "required": True, "placeholder": "64"},
                        {"name": "z1", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "x2", "type": "string", "required": True, "placeholder": "10"},
                        {"name": "y2", "type": "string", "required": True, "placeholder": "70"},
                        {"name": "z2", "type": "string", "required": True, "placeholder": "10"},
                        {"name": "blockType", "type": "string", "required": True, "placeholder": "STONE"},
                    ],
                },
                {
                    "id": "damage-entity",
                    "name": "DamageEntity",
                    "type": "action",
                    "description": "Deal damage to an entity",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "amount", "type": "string", "required": True, "placeholder": "5.0"},
                    ],
                },
                {
                    "id": "set-entity-health",
                    "name": "SetEntityHealth",
                    "type": "action",
                    "description": "Set entity health",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "health", "type": "string", "required": True, "placeholder": "20.0"},
                    ],
                },
                {
                    "id": "teleport-entity",
                    "name": "TeleportEntity",
                    "type": "action",
                    "description": "Teleport an entity to coordinates",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "x", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y", "type": "string", "required": True, "placeholder": "64"},
                        {"name": "z", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "world", "type": "string", "required": False, "placeholder": "world"},
                    ],
                },
                {
                    "id": "set-entity-velocity",
                    "name": "SetEntityVelocity",
                    "type": "action",
                    "description": "Set entity velocity",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "x", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "y", "type": "string", "required": True, "placeholder": "1"},
                        {"name": "z", "type": "string", "required": True, "placeholder": "0"},
                    ],
                },
                {
                    "id": "apply-entity-potion-effect",
                    "name": "ApplyEntityPotionEffect",
                    "type": "action",
                    "description": "Apply potion effect to entity",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "effectType", "type": "string", "required": True, "placeholder": "SPEED"},
                        {"name": "duration", "type": "string", "required": True, "placeholder": "200"},
                        {"name": "amplifier", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "set-entity-on-fire",
                    "name": "SetEntityOnFire",
                    "type": "action",
                    "description": "Set entity on fire",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "ticks", "type": "string", "required": True, "placeholder": "100"},
                    ],
                },
                {
                    "id": "set-entity-custom-name",
                    "name": "SetEntityCustomName",
                    "type": "action",
                    "description": "Set entity custom name",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "name", "type": "string", "required": True, "placeholder": "Boss"},
                    ],
                },
                {
                    "id": "set-entity-equipment",
                    "name": "SetEntityEquipment",
                    "type": "action",
                    "description": "Set entity equipment",
                    "color": "#e74c3c",
                    "properties": [
                        {"name": "helmet", "type": "string", "required": False, "placeholder": "IRON_HELMET"},
                        {"name": "chestplate", "type": "string", "required": False, "placeholder": "IRON_CHESTPLATE"},
                        {"name": "leggings", "type": "string", "required": False, "placeholder": "IRON_LEGGINGS"},
                        {"name": "boots", "type": "string", "required": False, "placeholder": "IRON_BOOTS"},
                        {"name": "mainHand", "type": "string", "required": False, "placeholder": "IRON_SWORD"},
                        {"name": "offHand", "type": "string", "required": False, "placeholder": "SHIELD"},
                    ],
                },
                {
                    "id": "set-thunder",
                    "name": "SetThunder",
                    "type": "action",
                    "description": "Set thunder state and duration",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "thunder", "type": "string", "required": True, "placeholder": "false"},
                        {"name": "duration", "type": "string", "required": False, "placeholder": "6000"},
                    ],
                },
                {
                    "id": "spawn-entity",
                    "name": "SpawnEntity",
                    "type": "action",
                    "description": "Spawn an entity at the player location",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "entityType", "type": "string", "required": True, "placeholder": "ZOMBIE"},
                    ],
                },
                {
                    "id": "strike-with-lightning",
                    "name": "StrikeWithLightning",
                    "type": "action",
                    "description": "Strike lightning at player location",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "damage", "type": "string", "required": False, "placeholder": "true"},
                    ],
                },
                {
                    "id": "spawn-particles",
                    "name": "SpawnParticles",
                    "type": "action",
                    "description": "Spawn particles at player location",
                    "color": "#27ae60",
                    "properties": [
                        {"name": "particle", "type": "string", "required": True, "placeholder": "HEART"},
                        {"name": "count", "type": "string", "required": False, "placeholder": "10"},
                        {"name": "offsetX", "type": "string", "required": False, "placeholder": "0"},
                        {"name": "offsetY", "type": "string", "required": False, "placeholder": "0"},
                        {"name": "offsetZ", "type": "string", "required": False, "placeholder": "0"},
                        {"name": "speed", "type": "string", "required": False, "placeholder": "0"},
                    ],
                },
                {
                    "id": "execute-command-as-player",
                    "name": "ExecuteCommandAsPlayer",
                    "type": "action",
                    "description": "Execute a command as the player",
                    "color": "#9b59b6",
                    "properties": [
                        {"name": "command", "type": "string", "required": True, "placeholder": "say Hello"},
                    ],
                },
                # Command Argument Blocks
                {
                    "id": "string-arg",
                    "name": "StringArg",
                    "type": "action",
                    "description": "Declare a typed string command argument",
                    "color": "#16a085",
                    "properties": [
                        {"name": "argName", "type": "string", "required": True, "placeholder": "targetName"},
                        {"name": "required", "type": "string", "required": False, "placeholder": "true"},
                        {"name": "defaultValue", "type": "string", "required": False, "placeholder": "guest"},
                    ],
                },
                {
                    "id": "player-arg",
                    "name": "PlayerArg",
                    "type": "action",
                    "description": "Declare a typed player command argument",
                    "color": "#16a085",
                    "properties": [
                        {"name": "argName", "type": "string", "required": True, "placeholder": "targetPlayer"},
                        {"name": "required", "type": "string", "required": False, "placeholder": "true"},
                    ],
                },
                {
                    "id": "integer-arg",
                    "name": "IntegerArg",
                    "type": "action",
                    "description": "Declare a typed integer command argument",
                    "color": "#16a085",
                    "properties": [
                        {"name": "argName", "type": "string", "required": True, "placeholder": "amount"},
                        {"name": "required", "type": "string", "required": False, "placeholder": "true"},
                        {"name": "defaultValue", "type": "string", "required": False, "placeholder": "1"},
                        {"name": "min", "type": "string", "required": False, "placeholder": "0"},
                        {"name": "max", "type": "string", "required": False, "placeholder": "100"},
                    ],
                },
                # GUI Menus
                {
                    "id": "create-gui",
                    "name": "CreateGUI",
                    "type": "action",
                    "description": "Create a chest GUI inventory",
                    "color": "#1abc9c",
                    "properties": [
                        {"name": "guiTitle", "type": "string", "required": True, "placeholder": "My Menu"},
                        {"name": "guiRows", "type": "string", "required": False, "placeholder": "3"},
                    ],
                },
                {
                    "id": "add-gui-item",
                    "name": "AddGUIItem",
                    "type": "action",
                    "description": "Add an item to the GUI at a specific slot",
                    "color": "#1abc9c",
                    "properties": [
                        {"name": "slot", "type": "string", "required": True, "placeholder": "0"},
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "DIAMOND"},
                        {"name": "displayName", "type": "string", "required": False, "placeholder": "Click Me"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "open-gui",
                    "name": "OpenGUI",
                    "type": "action",
                    "description": "Open the GUI for the player",
                    "color": "#1abc9c",
                    "properties": [],
                },
                # Temporary Variables
                {
                    "id": "set-temp-var",
                    "name": "SetTempVar",
                    "type": "action",
                    "description": "Set a temporary variable for this event execution",
                    "color": "#34495e",
                    "properties": [
                        {"name": "varName", "type": "string", "required": True, "placeholder": "selected_item"},
                        {"name": "value", "type": "string", "required": True, "placeholder": "%player%_value"},
                    ],
                },
                {
                    "id": "get-temp-var",
                    "name": "GetTempVar",
                    "type": "action",
                    "description": "Read a temporary variable and send it to the player",
                    "color": "#34495e",
                    "properties": [
                        {"name": "varName", "type": "string", "required": True, "placeholder": "selected_item"},
                        {"name": "messageFormat", "type": "string", "required": False, "placeholder": "Value: %value%"},
                    ],
                },
                # Boss Bar
                {
                    "id": "create-boss-bar",
                    "name": "CreateBossBar",
                    "type": "action",
                    "description": "Create and show a boss bar to the player",
                    "color": "#e91e63",
                    "properties": [
                        {"name": "title", "type": "string", "required": True, "placeholder": "Boss Bar Title"},
                        {"name": "color", "type": "string", "required": False, "placeholder": "RED"},
                        {"name": "style", "type": "string", "required": False, "placeholder": "SOLID"},
                        {"name": "progress", "type": "string", "required": False, "placeholder": "1.0"},
                    ],
                },
                {
                    "id": "remove-boss-bar",
                    "name": "RemoveBossBar",
                    "type": "action",
                    "description": "Remove a boss bar from the player",
                    "color": "#e91e63",
                    "properties": [
                        {"name": "title", "type": "string", "required": True, "placeholder": "Boss Bar Title"},
                    ],
                },
                # Scoreboard
                {
                    "id": "set-scoreboard",
                    "name": "SetScoreboard",
                    "type": "action",
                    "description": "Create and display a scoreboard to the player",
                    "color": "#ff9800",
                    "properties": [
                        {"name": "title", "type": "string", "required": True, "placeholder": "My Scoreboard"},
                        {"name": "lines", "type": "string", "required": True, "placeholder": "Line 1|Line 2|Line 3"},
                    ],
                },
                {
                    "id": "remove-scoreboard",
                    "name": "RemoveScoreboard",
                    "type": "action",
                    "description": "Remove the custom scoreboard from the player",
                    "color": "#ff9800",
                    "properties": [],
                },
                # Config & Data Persistence
                {
                    "id": "save-config",
                    "name": "SaveConfig",
                    "type": "action",
                    "description": "Save a value to the plugin config file",
                    "color": "#607d8b",
                    "properties": [
                        {"name": "path", "type": "string", "required": True, "placeholder": "players.%player%.kills"},
                        {"name": "value", "type": "string", "required": True, "placeholder": "1"},
                    ],
                },
                {
                    "id": "send-config-value",
                    "name": "SendConfigValue",
                    "type": "action",
                    "description": "Send a config value as a message to the player",
                    "color": "#607d8b",
                    "properties": [
                        {"name": "path", "type": "string", "required": True, "placeholder": "players.%player%.kills"},
                        {"name": "messageFormat", "type": "string", "required": False, "placeholder": "Your kills: %value%"},
                    ],
                },
                # Custom Recipes
                {
                    "id": "add-shapeless-recipe",
                    "name": "AddShapelessRecipe",
                    "type": "action",
                    "description": "Register a shapeless crafting recipe on enable",
                    "color": "#795548",
                    "properties": [
                        {"name": "recipeKey", "type": "string", "required": True, "placeholder": "my_recipe"},
                        {"name": "resultItem", "type": "string", "required": True, "placeholder": "DIAMOND"},
                        {"name": "resultAmount", "type": "string", "required": False, "placeholder": "1"},
                        {"name": "ingredients", "type": "string", "required": True, "placeholder": "COAL,COAL,COAL,COAL"},
                    ],
                },
                # Cooldown System
                {
                    "id": "set-cooldown",
                    "name": "SetCooldown",
                    "type": "action",
                    "description": "Set a cooldown timer for the player",
                    "color": "#8e44ad",
                    "properties": [
                        {"name": "cooldownName", "type": "string", "required": True, "placeholder": "my_cooldown"},
                        {"name": "duration", "type": "string", "required": True, "placeholder": "5"},
                        {"name": "cooldownMessage", "type": "string", "required": False, "placeholder": "Please wait %remaining% seconds!"},
                    ],
                },
                # Scheduled Tasks
                {
                    "id": "delay-action",
                    "name": "DelayAction",
                    "type": "action",
                    "description": "Execute following actions after a delay (uses BukkitRunnable)",
                    "color": "#8e44ad",
                    "properties": [
                        {"name": "delayTicks", "type": "string", "required": True, "placeholder": "20"},
                    ],
                },
                {
                    "id": "repeat-action",
                    "name": "RepeatAction",
                    "type": "action",
                    "description": "Repeat following actions at interval (uses BukkitRunnable)",
                    "color": "#8e44ad",
                    "properties": [
                        {"name": "intervalTicks", "type": "string", "required": True, "placeholder": "20"},
                        {"name": "repeatCount", "type": "string", "required": False, "placeholder": "0 (infinite)"},
                    ],
                },
                # Explicit branching blocks
                {
                    "id": "branch-if",
                    "name": "BranchIf",
                    "type": "action",
                    "description": "Start an explicit if branch with optional AND/OR second condition",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "firstType", "type": "string", "required": False, "placeholder": "HasPermission"},
                        {"name": "firstPermission", "type": "string", "required": False, "placeholder": "myplugin.admin"},
                        {"name": "firstItemType", "type": "string", "required": False, "placeholder": "DIAMOND"},
                        {"name": "firstAmount", "type": "string", "required": False, "placeholder": "1"},
                        {"name": "firstWorld", "type": "string", "required": False, "placeholder": "world"},
                        {"name": "firstHealth", "type": "string", "required": False, "placeholder": "5"},
                        {"name": "firstGameMode", "type": "string", "required": False, "placeholder": "SURVIVAL"},
                        {"name": "firstCooldownName", "type": "string", "required": False, "placeholder": "my_cooldown"},
                        {"name": "combinator", "type": "string", "required": False, "placeholder": "AND"},
                        {"name": "secondType", "type": "string", "required": False, "placeholder": "None"},
                        {"name": "secondPermission", "type": "string", "required": False, "placeholder": "myplugin.vip"},
                        {"name": "secondItemType", "type": "string", "required": False, "placeholder": "EMERALD"},
                        {"name": "secondAmount", "type": "string", "required": False, "placeholder": "1"},
                        {"name": "secondWorld", "type": "string", "required": False, "placeholder": "world"},
                        {"name": "secondHealth", "type": "string", "required": False, "placeholder": "10"},
                        {"name": "secondGameMode", "type": "string", "required": False, "placeholder": "CREATIVE"},
                        {"name": "secondCooldownName", "type": "string", "required": False, "placeholder": "my_cooldown"},
                    ],
                },
                {
                    "id": "branch-else",
                    "name": "BranchElse",
                    "type": "action",
                    "description": "Start the else branch for the latest BranchIf",
                    "color": "#f39c12",
                    "properties": [],
                },
                {
                    "id": "branch-end-if",
                    "name": "BranchEndIf",
                    "type": "action",
                    "description": "Close the latest BranchIf block",
                    "color": "#f39c12",
                    "properties": [],
                },
                # Condition Blocks (guard clauses)
                {
                    "id": "condition-has-permission",
                    "name": "HasPermission",
                    "type": "action",
                    "description": "Only run following actions if player has a permission node",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "permission", "type": "string", "required": True, "placeholder": "myplugin.admin"},
                    ],
                },
                {
                    "id": "condition-has-item",
                    "name": "HasItem",
                    "type": "action",
                    "description": "Only run following actions if player has a specific item in inventory",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "itemType", "type": "string", "required": True, "placeholder": "DIAMOND"},
                        {"name": "amount", "type": "string", "required": False, "placeholder": "1"},
                    ],
                },
                {
                    "id": "condition-health-above",
                    "name": "HealthAbove",
                    "type": "action",
                    "description": "Only run following actions if player health is above a threshold",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "health", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "condition-health-below",
                    "name": "HealthBelow",
                    "type": "action",
                    "description": "Only run following actions if player health is below a threshold",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "health", "type": "string", "required": True, "placeholder": "5"},
                    ],
                },
                {
                    "id": "condition-gamemode-equals",
                    "name": "GameModeEquals",
                    "type": "action",
                    "description": "Only run following actions if player is in a specific game mode",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "gameMode", "type": "string", "required": True, "placeholder": "SURVIVAL"},
                    ],
                },
                {
                    "id": "condition-is-in-world",
                    "name": "IsInWorld",
                    "type": "action",
                    "description": "Only run following actions if player is in a specific world",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "world", "type": "string", "required": True, "placeholder": "world"},
                    ],
                },
                {
                    "id": "condition-is-sneaking",
                    "name": "IsSneaking",
                    "type": "action",
                    "description": "Only run following actions if player is sneaking",
                    "color": "#f39c12",
                    "properties": [],
                },
                {
                    "id": "condition-is-flying",
                    "name": "IsFlying",
                    "type": "action",
                    "description": "Only run following actions if player is flying",
                    "color": "#f39c12",
                    "properties": [],
                },
                {
                    "id": "condition-is-op",
                    "name": "IsOp",
                    "type": "action",
                    "description": "Only run following actions if player is an operator",
                    "color": "#f39c12",
                    "properties": [],
                },
                {
                    "id": "condition-hunger-above",
                    "name": "HungerAbove",
                    "type": "action",
                    "description": "Only run following actions if player food level is above threshold",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "hunger", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "condition-hunger-below",
                    "name": "HungerBelow",
                    "type": "action",
                    "description": "Only run following actions if player food level is below threshold",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "hunger", "type": "string", "required": True, "placeholder": "5"},
                    ],
                },
                {
                    "id": "condition-level-above",
                    "name": "LevelAbove",
                    "type": "action",
                    "description": "Only run following actions if player experience level is above threshold",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "level", "type": "string", "required": True, "placeholder": "10"},
                    ],
                },
                {
                    "id": "check-cooldown",
                    "name": "CheckCooldown",
                    "type": "action",
                    "description": "Only run following actions if player is NOT on cooldown",
                    "color": "#f39c12",
                    "properties": [
                        {"name": "cooldownName", "type": "string", "required": True, "placeholder": "my_cooldown"},
                        {"name": "cooldownMessage", "type": "string", "required": False, "placeholder": "Please wait %remaining% seconds!"},
                    ],
                },
            ],
            "custom_options": [
                {
                    "id": "custom-condition",
                    "name": "Custom Condition",
                    "type": "custom-condition",
                    "description": "Write custom Java logic for a condition",
                    "color": "#f39c12",
                    "properties": [],
                },
                {
                    "id": "custom-action",
                    "name": "Custom Action",
                    "type": "custom-action",
                    "description": "Write custom Java code for an action",
                    "color": "#9b59b6",
                    "properties": [],
                },
            ],
        }
